// TypeScript file
ImportType(IGlobal);
var LOAD_ALWAYS = 0; //-- 第一次使用时加载，流程切换不卸载
var LOAD_RECYCLE = 1; //-- 每次使用时才加载，每次关闭窗口卸载 （调用 ..._Unload()函数）
var LOAD_RECYCLE_STATE = 2; //-- 每次使用时才加载，流程切换回收资源 （调用 ..._Unload()函数）
var WndsMap = (_a = {},
    _a["Common"] = (_b = {},
        //["TapTipsFrame"]:{mode:LOAD_ALWAYS, path:"", autoshow:false, init:false},
        _b["CommonTipsFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false, common: true, uievent: false },
        _b["MsgWaitingFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: true, common: true, uievent: false },
        _b["IconMsgFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false, common: true },
        _b["ScreenEffectTipsFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false, common: true, uievent: false },
        _b["ConfirmFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false, common: true },
        _b["LoginFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false, common: true },
        _b),
    _a[PRECEDURE_LOGIN] = (_c = {},
        _c["LoginServerListFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _c["LoginRegisterFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _c["LoginCreateRoleFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _c["LoginRoleListFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _c),
    _a[PRECEDURE_GAME] = (_d = {},
        //主界面
        _d["MainFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: true, init: false },
        _d["MainContentFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: true, init: false },
        _d["MainCityFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //["MainMoreFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //["ThumbnailFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["SettingFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //["ActivityShareFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["ChatInChannelFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: true },
        _d["ChatInsertFaceFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ChatBubbleSelectFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ChatDisplaySelectFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //主界面-圣地
        // ["RobberDoubleFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["RobberRecordFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["RobberBossFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["RobberDropListFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["RobberRatioFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //角色绑定的窗口
        _d["CharacterUpperFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false, uievent: false },
        _d["CharacterFightFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false, uievent: false },
        _d["CharacterAwardFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false, uievent: false },
        _d["ChatBubbleFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false, uievent: false },
        //背包
        _d["ItemBeiBaoFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["BeiBaoAddCapacityFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["BeiBaoSmelteFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //物品
        //["ItemPickFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ItemHintFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //["ItemResolveLottoFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //["ItemResolveFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ItemBatchUseFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ItemRecommendFrame"] = { mode: LOAD_RECYCLE_STATE, path: "", autoshow: false, init: true },
        _d["ItemChooseFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ItemOneKeyResolveFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ChangeNameFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //装备
        // ["EquipBeiBaoFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["EquipProgressFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["EquipMakeFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["EquipMakeListFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // //["EquipEnhanceFrame"]:{mode:LOAD_ALWAYS, path:"", autoshow:false, init:false},
        // ["EquipFactoryFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["EquipResonanceFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["EquipOneKeyIntensifyFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //["ShopFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //["ShopBuyFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //["ShopSupriseFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["ShopYuanBaoFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["ShopEquipFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["ShopZhuangBanFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["ShopJingJiFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["ShopItemBuyFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //关卡界面
        //["CopyCardFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["CampaignBossFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["CampaignRankFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //通用
        //["CommonEmbattleFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["QuickGainFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["QuickGainUpgradeFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["NotifyPrizeGainFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["PrizeRareShowFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["PrizeShowFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //["ActorShowFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ActivityWaitFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["MainPlayerFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["PlayerListFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["PlayerAttackFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["RuleDescribeFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //["OneKeyToEquipFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ActivityPrizeFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // //战斗
        _d["FightFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: true },
        _d["FightPrizeFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["FightCapturePrizeFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["FightLostFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["FightAttackFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: true },
        // ["FightRecordFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["FightLadderFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //["FightPVPFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["FightFacWarFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //宠物--
        _d["PetFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //["PetUpgradeFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //["PetBreakFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //["PetLinkFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["PetListFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["PetPickSoulFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["PetStoneFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["PetStoneUpgradeFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //["PetWakeFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //["PetSkillUpgradeFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["PetPreviewFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["PetSummonFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["PetSummonAllPetFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["PetSummonAllItemFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["PetSummonReplayFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["PetCombatForceTipsFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: true },
        // ["GoddessEvolutionFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["PetMagicCircleFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: true },
        // ["PetSummonPrizeFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //["PetCapabilityDetailFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["PetClearFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["PetAttributeFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["PetAttrAddFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["PetChangeNameFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["PetNaturlFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["PetEmbattleFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //女神之吻
        // ["GoddessKissFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["GoddessKissAnimFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //职业
        // ["ProfessionFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["ProfessionLotteryFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //["ProfessionSkillUpgradeFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //御灵
        // ["SacrificeFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["SacrificeLevelFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // //养成
        // ["GrowFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["GrowEventFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["GrowEventListFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["GrowFinishReportFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["GrowPrizeFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["GrowPrizeAnimFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["TaskDialogFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //剧情电影
        _d["MovieDramaFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: true },
        _d["FullBalckFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["FastEndMoiveFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: true },
        _d["MovieBackGroundFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["FullImageFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //好友
        _d["DeleteFriendFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //["FriendChatFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["FriendFindResultFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["FriendsFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["FindFriendFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //帮会
        _d["ClubFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubListFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubCreatFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubActiveFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubBuyFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubChangeNoticeFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubDonateFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubMapFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubPeopleApplyFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubPeopleInfoFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubAppointFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubChangeNameFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubActivePrizeFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubExchangeFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ClubEventRecordFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //神兵
        // ["ImmortalsFrame"]: {  	mode: LOAD_ALWAYS,   path: "", 		autoshow: false, init: false},	
        // ["ImmortalsCapabilityDetailFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ImmortalsListFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ImmortalsTipFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //评分
        // ["GradeFrame"]: {  	mode: LOAD_RECYCLE_STATE,   path: "", 		autoshow: false, init: false},	
        // ["AllComparisonGradeFrame"]: {  	mode: LOAD_RECYCLE_STATE,   path: "", 		autoshow: false, init: false},	
        // ["PersonageComparisonGradeFrame"]: {  	mode: LOAD_RECYCLE_STATE,   path: "", 		autoshow: false, init: false},	
        //邮件
        _d["MailListFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["MailFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: true },
        // //试炼场
        // ["SkyTowerFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["SkyTowerPrizeFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["SkyTowerReviveAndResetFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["SkyTowerEmbattleFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["SkyTowerTimerFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // //守护
        // ["DefendFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["DefendCapabilityDetailFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["DefendLevelFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["DefendOpenHoldFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["DefendSkillEmbedFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["DefendSkillLockFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["DefendAngleWingFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //公会
        // ["ClubWelcomeFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubCreateFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubIconFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubListFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        // ["ClubAppointFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubAppointSelectFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubRepoFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // //["ClubWarPointRankFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubRepoRecordFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubRepoAllocFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubCompetitionFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubComptContributeFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubCompeRidePreviewFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //公会战
        // ["ClubWarEntryFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubWarListFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubWarEliteBattleFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubWarEliteEntryFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubWarEliteReadyFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubWarEmbattleTeamFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubWarMainFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubWarPointDetailFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubWarWorshipFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // //世界BOSS
        // ["BigBossAutoFightFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["BigBossFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["BigBossInspireFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["BigBossKillRankFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["BigBossTipsFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // //矿洞
        // ["NavigationChooseAreaFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["NavigationChooseResFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["NavigationDetailFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["NavigationFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["NavigationLogFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["NavigationRankFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // //公会副本 
        // ["ClubFubenListFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubFubenEntryFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ClubFubenFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //竞技场
        _d["ChampionFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["ChampionRankFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ChampionRecordFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ChampionHighPrizeFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ChampionAwardFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //活动
        _d["ActivityRankBaseFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: true },
        _d["ActivityListFrame"] = { mode: LOAD_RECYCLE_STATE, path: "", autoshow: false, init: true },
        _d["AnswerQuestionFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: true },
        //冲值活动
        //["PayActivityEntryFrame"]: { mode: LOAD_RECYCLE_STATE, path: "", autoshow: false, init: false },
        // ["PayActivityFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["PaySellPetFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //储值
        _d["PayFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["GoldBuyFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: true },
        _d["VIPFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //首充
        //["ShouChongFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //投资
        _d["TouZiFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //寻宝
        //["XunBaoFrame"]: { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //天女
        _d["TianNvFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //天仙
        _d["TianXianFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //仙侣
        _d["XianLvFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["XianLvAttributeFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["XianLvPropertyFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["XianLvQiYuanFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["XianLvFightFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["XianLvSkillDesFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //日常
        _d["DailyFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["DailyGhostFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["DailyPrizeTipsFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["DailyFindBackFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["DailyFindBackTipsFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //通用
        _d["CommonDrugFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["CommonSkinsFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["CommonSkinPropertyFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["CommonFunPropertyFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["CommonOpenTipsFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["FullScreenBgFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: true },
        _d["ItemBoxPreviewFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //角色
        _d["RoleFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["RoleMountsDanFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["RoleMountsSkinsFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["RoleSkillsSettingFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["RoleFATFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["RoleFashionPeopleFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["RolePropertyFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["RoleFaBaoFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["RoleFaBaoQualityFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["FaBaoItemTipsFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //锻造
        _d["ForgeFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["ForgeLevelFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //离线收益
        _d["PlayerOffLineFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //西游护送
        _d["OdysseyEscortFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["EscortPrizeFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["EscortFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["InterceptRecordFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["InterceptTipsFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["EscortTipsFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["RevengeTipsFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //玩家详情
        _d["PlayerDetailsFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["PlayerDetailsRenameFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["PlayerDetailsSettingFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //获取途径
        _d["GoodsAsseceFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["MoneyChargeFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //排行榜
        _d["RankFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["AnimTipsFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["MovableAnimTipsFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["DramaTipsFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["GuideMaskFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["GuideTipsFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["FuncPreviewFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ActivateButtonFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ActivateButtonGiftFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["ActivateButtonMonthFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //公告
        _d["NoticeListFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: true },
        _d["UpdateNoticeFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["NoticeDetailFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //离线奖励
        //["RobberOfflineSettingFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //通用系统页面
        _d["FunSkillFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //BOSS、副本
        _d["BossMainFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["BossGlobalRemindFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["BossWildFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["BossBefallFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["CopyMainFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["CopyStarRankFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["CopyTempleRankFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["BossWildFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        // ["BossBefallFrame"]: { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //关卡大地图
        _d["MapFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //充值活动
        _d["DailyLoginFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["PayStageUpFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["DailyPayFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d["TodayGiftsFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //福利大厅
        _d["WelfareFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        //寻宝
        _d["LuckyFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //三生三世
        _d["SanShengSanShiFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["ProposeFrame"] = { mode: LOAD_RECYCLE, path: "", autoshow: false, init: false },
        _d["MarryInformFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        //跨服
        _d["GlobalMainFrame"] = { mode: LOAD_ALWAYS, path: "", autoshow: false, init: false },
        _d),
    _a);
var GlobalForbidMap = (_e = {},
    _e["click"] = [
        "MainMenuFrame",
    ],
    _e["exclude"] = [],
    _e["show"] = [
        //"MapNameTipsFrame",
        "DailySignInFrame",
        "NoticeListFrame",
        "IconMsgFrame",
    ],
    _e);
var MainAutoHideUI = (_f = {},
    _f["RoleFrame"] = true,
    _f["ForgeFrame"] = true,
    _f["XianLvFrame"] = true,
    _f["PetFrame"] = true,
    _f["MainCityFrame"] = true,
    _f["ClubFrame"] = true,
    _f["ChampionFrame"] = true,
    _f["ActivityListFrame"] = true,
    _f["CopyMainFrame"] = true,
    _f["GlobalMainFrame"] = true,
    _f["BossMainFrame"] = true,
    _f);
var _a, _b, _c, _d, _e, _f;
//# sourceMappingURL=WndMapping.js.map