var skillEffectFunOptions = {
    //fight
    fightInitExecute: 1,
    //fightEndExecute					: 2,//技能结束时要执行的，一般是升级时，先要旧的停止，再生成新的
    fightUseExecute: 3,
    fightBeforeSortExecute: 4,
    //fightCmdStartExecute		: 5,//命令开始时要执行的
    //fightCmdEndExecute			: 6,//命令结束时要执行的
    fightBeforeAttack: 7,
    //combat
    combatInitExecute: 11,
    combatEndExecute: 12,
    //combatUseExecute				:	14,//战斗中使用技能要执行的
    //live
    liveUseExecute: 20,
    liveInitExecute: 21,
    liveEndExecute: 22,
};
var skillConst = {
    RANK_MAX: 5,
    BUFFS_MAX: 32,
    TARGET_IS_FIGHTER: 2,
    TARGET_IS_PROTECTOR: 3,
    SERIES_ATTACK: 805,
    CHASH_ATTACK: 801,
    NEWBIE_FLY: 804,
    GENERAL_ATTACK_SKILLID: 801,
    WIPE_GHOST_SKILLS: [60009, 70009],
    GHOST_SKILLS: [60008, 70008],
    LOW_QUALITY_SKILL_BEGIN: 60000,
    HIGH_QUALITY_SKILL_BEGIN: 70000,
    SCHOOL_SPECIAL_SKILL_ID_BEGIN: 900,
    PRE_BUFF_SKILLS: [10103, 11007],
    PRE_BUFFS: ['gaosuzt', 'pilaozt'],
};
var skillOpResult = {
    SUCCESS: 0,
    MISS: 1,
    NO_TARGETS: 2,
    HP_NOT_ENOUGH: 3,
    MP_NOT_ENOUGH: 4,
    HPPercent_NOT_ENOUGH: 5,
    MPPercent_NOT_ENOUGH: 6,
    RP_NOT_ENOUGH: 7,
    HIDE_NOT_ENOUGH: 8,
    IMMUNIZED: 9,
    SKILL_IN_CD: 10,
    NO_NEED_BUFF: 11,
    CANT_USE_IN_DAY: 12,
    CANT_USE_IN_NIGHT: 13,
    NO_SKILL: 14,
    HP_TOO_MUCH: 15,
    MP_TOO_MUCH: 16,
    HPPercent_TOO_MUCH: 17,
    MPPercent_TOO_MUCH: 18,
    HIDE_CANT_USE: 19,
    SUMMON_REPEAT: 20,
    TARGET_NOT_NEED_RELIVE: 21,
    TARGET_CANT_RELIVE: 22,
    PHYSICAL_LIMITED: 23,
    SKILL_LIMITED: 24,
    ITEM_USE_LIMITED: 25,
    CANT_ESCAPE: 26,
};
var skillTargetMethod = {
    NOTDEFINE: 1,
    NORMAL: 2,
    SELF: 3,
    ALL: 4,
    ENEMYS: 5,
    ALLYS: 6,
    ALLYMATE: 7,
    RANDOM: 8,
    ROW: 9,
    OPROW: 10,
    COL: 11,
    MULTI: 12,
    MAXLL: 13,
    MAXZL: 14,
    MAXMJ: 15,
    MAXTL: 16,
    CROSS: 17,
    RANDOMALLY: 18,
    ROWALLY: 19,
    OPROWALLY: 20,
    FIX: 21,
    AHEAD: 22,
    ENEMYSORFORCE: 23,
    TARGET_ROW: 24,
    NORMAL_OPPOSITE: 25,
    OPROW_CROSS: 26,
    MY_ROW: 27,
    MAX_DODGE: 28,
    RANDOMS: 29,
    BUFFS: 30,
    RANDT_SIDE: 31,
    COL_QUEUE: 32,
    BUFFSELECT: 33,
    ALLYMATE_MINRP: 34,
    RANDOMFRONT: 35,
    LOWROW: 36,
    OPROWPET: 37,
    ALLYMATE_PERCENT: 38,
    LOWALL: 39,
    ADDENEMYS: 40,
    SEQUENCE: 41,
    ALLY_HP_VALUE_SORT: 42,
    ALLY_HP_VALUE_LOWER: 44,
    ALLY_HPVALUE_HIGHER: 48,
    ALLY_HPPER_HIGHER: 47,
    ENEMY_HPVALUE_HIGHER: 49,
    FIX_GROUP: 50,
    SEQUENCE_NUM: 51,
    ALLAY_COL: 52,
    ALLAY_COL_EX: 53,
    ENEMY_SORT_RP: 54,
    ENEMYOPROWPET: 55,
};
//技能大类
var skillSuperType = {
    PASSTIVE: 0,
    AUTO: 1,
    MANUAL: 2,
    ESOTERIC: 3,
    CAPTURE: 4,
};
//技能对应技能升级消耗系数
var skillTypeToConsumeRatio = (_a = {},
    _a[skillSuperType.AUTO] = 1,
    _a[skillSuperType.MANUAL] = 2,
    _a[skillSuperType.ESOTERIC] = 1.5,
    _a);
var _a;
//# sourceMappingURL=skillOptions.js.map